resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/Harshkarira/ETL
      branch: master

jobs:
  - name: download-reliance-data
    plan:
      - get: git-repo
        trigger: true
      - task: fetch-creds
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9-slim"

          params:
            VAULT_ADDR: 'http://vault:8200'
            VAULT_TOKEN: 'root-token'

          run:
            path: /bin/sh
            args:
              - -c
              - |
                export VAULT_ADDR='http://vault:8200'
                export VAULT_TOKEN='root-token'

                USERNAME=$(vault kv get -field=username secret/screener)
                PASSWORD=$(vault kv get -field=password secret/screener)

                export VAULT_USERNAME=$USERNAME
                export VAULT_PASSWORD=$PASSWORD

                echo "Fetched Username: $VAULT_USERNAME"
                echo "Fetched Password: $VAULT_PASSWORD"

      - task: run-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9-slim"
          inputs:
            - name: git-repo
          outputs:
            - name: downloaded-files
          run:
            path: sh
            args:
              - -exc
              - |
                apt-get update && apt-get install -y wget unzip
                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                apt-get install -y ./google-chrome-stable_current_amd64.deb
                pip install selenium webdriver-manager
                pip install pandas
                cd git-repo
                python script.py
                mv "Reliance Industr.xlsx" ../downloaded-files/
          params:
            USERNAME: $VAULT_USERNAME
            PASSWORD: $VAULT_PASSWORD